model_type: "oh"  # Options: "oh" (one-hot), "emb" (embedding)

dataset_settings:
  dataset_name: "complicated"  # Options: "easy", "complicated", "example"
  max_protein_length: 1000
  num_samples: 10000

# Ignore settings above until final dataset is ready (currently dont do anyting)


model_settings:
  cnn_dim: 256
  dropout: 0.1    # Not implemented yet #TODO
  dilation: 2
  kernel_size: 5

train_settings:
  batch_size: 128
  epochs: 10
  learning_rate: 0.00005
  lr_decay: 0.95

  seed: 42

  model_save_name: complicated_emb_1 #"random_oh_lr0001"  # Name of model to save (None for no saving)
